# Generated by Django 3.1.7 on 2021-02-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
