# Generated by Django 3.1.7 on 2021-02-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_article_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
