# Generated by Django 3.1.7 on 2021-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
